### PR TITLE
updated to latest jersey version

### PR DESCRIPTION
**Pull request by olensmar**
for improved compatibility with other frameworks

### CODE REVIEW

**Comment by fehguy** [comment]
@olensmar thanks--are there any known back-compatibility issues that you're aware of?

**Comment by olensmar** [comment]
nothing I'm aware of apart from that its now built with/for Java 7 instead of Java 6. Alternatively we could set the dependency as provided - since the inflector will probably mostly be used in scenarios where there is a jersey implementation already available!?

**Comment by olensmar** [comment]
thank you!

**Comment by fehguy** [comment]
I may have to revert this, it seems to have broken things.

**Comment by olensmar** [comment]
darn - what did it break? anything I can look into?

**Comment by fehguy** [comment]
I see these errors:

```
Exception in thread "Thread-16" java.lang.NoSuchFieldError: WRITE_DURATIONS_AS_TIMESTAMPS
	at com.fasterxml.jackson.datatype.joda.ser.DurationSerializer.<init>(DurationSerializer.java:28)
	at com.fasterxml.jackson.datatype.joda.ser.DurationSerializer.<init>(DurationSerializer.java:25)
	at com.fasterxml.jackson.datatype.joda.JodaModule.<init>(JodaModule.java:43)
	at io.swagger.client.JSON.<init>(JSON.java:22)
```

Which tells me there's probably a dependency in swagger-core on a joda library incompatible with the jackson or jersey versions here.

**Pull request merged**
