### PR TITLE
Support an allOf containing refs

### PR DESCRIPTION
**Pull request by joeljons**
I copied the logic from a RefProperty and applied it to a RefModel. Could there be some reason this wasn't added before which I missed?

### CODE REVIEW

**Comment by gracekarina** [comment]
Well, If I remember correctly, inflector should do a ResolveFully() at init, meaning that all Refs should be put inline in the Path that it's referencing it. It would be worth to review why it's the ref still there after, resolveFully. @joeljons

**Comment by joeljons** [comment]
@gracekarina I am only using the example builder and not the actual inflector. That could be the reason for working different for me maybe.

**Comment by gracekarina** [comment]
oki, it's merged. 👍

**Comment by joeljons** [comment]
On the other hand I think I do resolvefully too  ¯\_(ツ)_/¯

**Comment by gracekarina** [comment]
Hi @joeljons, I did added this to the test and commented the refModel code:
```@Test
    public void testAllOfAndRef() throws Exception {
        Swagger swagger = new SwaggerParser().read("src/test/swagger/allOfAndRef.yaml");
        ResolverUtil resolverUtil = new ResolverUtil();
        resolverUtil.resolveFully(swagger);

        Yaml.prettyPrint(swagger);

        String output = getExampleForPath(swagger, "/refToAllOf");
        assertEqualsIgnoreLineEnding(output, "{\n" +
                "  \"id\" : 4,\n" +
                "  \"username\" : \"trillian\"\n" +
                "}");
    }```

Can you please check and let me know :)

**Comment by gracekarina** [comment]
I see other tests using RefProperty and getting the example without using ResolverFully method.
So I think we should allow the RefModel code as well, but to be honest I'm not really sure when will be used the `ExampleBuilder` separately from inflector, because every time a `new Inflector()` instance is created, the ResolverFully is immediately used to resolve all refs. so in theory no ref should ever be at inflector.

**Comment by joeljons** [comment]
I actually didn't know about the `ResolverUtil` in inflector. I will start use that for my ExampleBuilder usage.

I verified that it works for me as well. I guess that means we could revert the changes I did in `ExampleBuilder.fromModel`!

**Pull request merged**
